### ISSUE TITLE
Database-less implementation

### ISSUE THREAD

**Issue by EmilCataranciuc** [markitosgv/JWTRefreshTokenBundle#188]
LexikJWTAuthenticationBundle provides a database-less implementation. Wouldn't it be possible to offer the same with this bundle?

**Comment by Jayfrown** [comment]
Not without sacrificing the revoke feature.

Not storing valid `refresh_token`s in a database, but validating purely on whether they cryptographically match some secret (like JWTs do) would yield always-valid `refresh_token`s, at least until their TTL expires (just like JWTs).

Currently you can do as follows:

1. Generate JWTs with a very low TTL.
2. Generate refresh_tokens with a higher TTL (about as long as you'd like a 'normal user session' to stay alive after closing the browser)
3. Your application can 'remember' logged-in users by testing if the current `refresh_token` is valid. I would recommend [using HttpOnly cookies](https://github.com/markitosgv/JWTRefreshTokenBundle#configure-refresh-token-in-cookie) for this, and just hitting the `/refresh` endpoint to see if it returns a new JWT.
3. Have your application hit the `/refresh` endpoint periodically
4. Have your application's logout feature invalidate the `refresh_token`

At this point the JWT is still usable and valid, but that's why it should have a *very* low TTL.

Implementing what you asked for, would make it impossible to revoke/invalidate a particular `refresh_token`.
