### ISSUE TITLE
setting ttl according to some user data

### ISSUE THREAD

**Issue by hmsuchier** [markitosgv/JWTRefreshTokenBundle#317]
Hi,
 Is there a way to set specific ttl according to, say, user roles for example? Best way I've found to do this so far is to set ttl to max needed duration, & to run a cron command to revoke tokens for users who need shorters ttl. Is there another way ?
Thanks.

**Comment by mbabker** [comment]
If the data you need is in the user object, you could override the `gesdinet.jwtrefreshtoken.refresh_token_generator` and use a custom implementation of `Gesdinet\JWTRefreshTokenBundle\Generator\RefreshTokenGeneratorInterface` that computes your custom TTL.  Otherwise, if you need more data than what is provided to the generator, your best options are either flat out replacing the `AttachRefreshTokenOnSuccessListener` event listener from this bundle and taking complete control of the token creation and attaching it to the response or adding an event listener for the `lexik_jwt_authentication.on_authentication_success` event to run after that listener has generated the token (but that one's tricky to get right because you have to manually find the right refresh token in the response data).

**Comment by hmsuchier** [comment]
Thank you for your answer. I finally listened to the` lexik_jwt_authentication.on_authentication_success` that is triggered at authentication time as well as at refresh time (totally makes sense). Then I can get all user data I want to set proper ttl time, find the token according to user, and update its TTL.
